version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./todo:/work

  web:
    build: ./infra/next
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd todo_web && npm run dev"
    ports:
      - "8080:80"

  db:
    hostname: db
    build: ./infra/mysql
    ports:
      - 3306:3306
    volumes:
      - ./infra/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
