version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.18-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    hostname: db
    build: ./infra/mysql
    ports:
      - 3306:3306
    volumes:
      - ./infra/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
